/*Write the program greater value in a two number using to the  IF Statements*/
#include<iostream>
using namespace std;
int main()
{

int f,s;
cout<<"Enter the first number\n";
cin>>f;
cout<<"Enter the second number\n";
cin>>s;
if(f>s)
    cout<<"first numbers is greater";
    if(f>s)
        cout<<"second number is greater";
    if(f==s)
        cout<<"Both are equal";
    return 0;
}
